In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.simplefilter("ignore")

In [2]:
df = pd.read_excel("Taxi_cleaned.xlsx")
df

,Trip_Distance_km,Passenger_Count,Per_Km_Rate,Trip_Duration_Minutes,Trip_Price,Time_of_Day_Evening,Time_of_Day_Morning,Time_of_Day_Night,Day_of_Week_Weekend,Traffic_Conditions_Low,Traffic_Conditions_Medium,Weather_Rain,Weather_Snow
0,5.279810,3,0.800000,53.82,36.2624,0,1,0,0,1,0,0,0
1,7.378374,1,1.210000,37.27,52.9032,1,0,0,1,0,0,0,0
2,6.690839,4,0.510000,116.81,36.4698,1,0,0,0,1,0,0,0
3,3.253939,2,1.710000,89.33,60.2028,0,0,0,1,0,1,0,0
4,1.733422,4,1.660000,5.05,11.2645,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,2.347067,4,0.620000,58.39,34.4049,0,0,0,1,0,1,0,0
854,8.213556,4,0.610000,61.96,62.1295,0,0,1,0,0,1,0,0
855,3.009442,3,1.780000,54.18,33.1236,0,1,0,0,1,0,1,0
856,8.350267,1,0.820000,114.94,61.2090,0,1,0,0,1,0,0,0
857,5.775474,3,1.233316,29.69,45.4437,0,1,0,1,0,1,0,0

In [3]:
X = df.drop("Trip_Price",axis = 1)
y = df["Trip_Price"]

### Train-test split

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8,random_state=54)

### Modelling

In [5]:
from sklearn.preprocessing import PolynomialFeatures
polynomial_converter = PolynomialFeatures(degree=2,include_bias=False)
X_train_poly = pd.DataFrame(polynomial_converter.fit_transform(X_train))
X_test_poly = pd.DataFrame(polynomial_converter.transform(X_test))

In [6]:
from sklearn.linear_model import LinearRegression
model1 = LinearRegression()
model1.fit(X_train_poly,y_train)

print("Intercept",model1.intercept_)
print("Coefficient",model1.coef_)

Intercept 18.023847523143075
Coefficient [-1.92242962e+01  2.70846903e+00 -1.60417592e+00  3.34129542e-01
  2.78521055e+00  2.37491262e+00  2.80639694e+00 -4.33007337e-01
  9.15717021e+00  6.19389639e+00  2.99177615e+00 -8.80110794e-01
  2.35007216e+00 -5.00525665e-01  6.22921158e+00  6.76685467e-03
 -6.04960998e-01 -5.30784703e-03 -2.30452631e+00  3.49064747e-01
 -2.66822544e+00 -2.09841935e+00 -3.56255280e-02 -3.36172318e+00
  6.00478780e-03  6.47920886e-01 -1.76269796e-03  3.39072376e-01
 -1.10254804e-02  2.56580674e+00 -6.19380872e-01 -6.96268057e-01
 -2.85669509e-01 -5.48505349e-01  3.87138351e+00 -3.08887802e+00
 -3.49166965e-02 -1.28105487e+00 -3.15505352e+00 -2.78640162e+00
  1.42288833e+00  1.09544556e-01  1.55272945e+00 -1.77400281e+00
  1.23308466e+00 -1.69179416e-04 -4.80884115e-02  6.70448898e-03
  6.22032373e-02 -2.89917285e-02 -1.45166104e-02  2.93774227e-02
  1.48918915e-02 -5.52035897e-02  2.78521055e+00  5.77315973e-15
 -3.55271368e-15 -6.90096209e-01  2.33020234e+00 -1.38628024e+00
 -1.57662213e-01 -3.49269287e+00  2.37491262e+00 -1.59872116e-14
 -2.07184132e+00 -1.50224931e+00 -3.83401335e+00  1.09493969e-01
  1.26532618e+00  2.80639694e+00  1.00639956e+00  6.80915845e+00
 -1.39689381e+00 -6.80675861e+00 -1.70849093e+01 -4.33007337e-01
 -1.96202895e+00  2.43316688e+00  7.97323281e-01 -6.65015671e+00
  9.15717021e+00  0.00000000e+00 -5.36506751e+00  1.97874374e+01
  6.19389639e+00 -4.54011535e+00  2.02048347e+01  2.99177615e+00
  0.00000000e+00 -8.80110794e-01]

### Prediction & Evaluation

In [7]:
ypred_train = model1.predict(X_train_poly)

from sklearn.metrics import mean_squared_error,r2_score
print("Train r2:",r2_score(y_train,ypred_train))

#Prediction on test data
ypred_test = model1.predict(X_test_poly)
print("Test R2:",r2_score(y_test,ypred_test))

from sklearn.model_selection import cross_val_score
print("Cross validation score:",cross_val_score(model1,X_train_poly,y_train,cv=5,scoring="r2").mean())

Train r2: 0.9072979926611976
Test R2: 0.8720008796833291
Cross validation score: 0.8550710115287536

In [8]:
import joblib
joblib.dump(model1,'polynomial.joblib')

['polynomial.joblib']