In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.simplefilter("ignore")

In [2]:
df = pd.read_excel("Taxi_cleaned.xlsx")
df

,Trip_Distance_km,Passenger_Count,Per_Km_Rate,Trip_Duration_Minutes,Trip_Price,Time_of_Day_Evening,Time_of_Day_Morning,Time_of_Day_Night,Day_of_Week_Weekend,Traffic_Conditions_Low,Traffic_Conditions_Medium,Weather_Rain,Weather_Snow
0,5.279810,3,0.800000,53.82,36.2624,0,1,0,0,1,0,0,0
1,7.378374,1,1.210000,37.27,52.9032,1,0,0,1,0,0,0,0
2,6.690839,4,0.510000,116.81,36.4698,1,0,0,0,1,0,0,0
3,3.253939,2,1.710000,89.33,60.2028,0,0,0,1,0,1,0,0
4,1.733422,4,1.660000,5.05,11.2645,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,2.347067,4,0.620000,58.39,34.4049,0,0,0,1,0,1,0,0
854,8.213556,4,0.610000,61.96,62.1295,0,0,1,0,0,1,0,0
855,3.009442,3,1.780000,54.18,33.1236,0,1,0,0,1,0,1,0
856,8.350267,1,0.820000,114.94,61.2090,0,1,0,0,1,0,0,0
857,5.775474,3,1.233316,29.69,45.4437,0,1,0,1,0,1,0,0

In [3]:
X = df.drop("Trip_Price",axis = 1)
y = df["Trip_Price"]

### Train-test split

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8,random_state=54)

**Applying hyperparameter tunning for Ridge regression**

In [5]:
from sklearn.model_selection import GridSearchCV

#model
from sklearn.linear_model import Ridge
estimator = Ridge()

#parameters and values
param_grid = {"alpha":list(range(1,100))}

#Identifying the best value of the parameter within given values for the given data
model_hp = GridSearchCV(estimator,param_grid,cv=5,scoring="r2")

model_hp.fit(X_train,y_train)

model_hp.best_params_

{'alpha': 12}

### Modelling

In [6]:
from sklearn.linear_model import Ridge
ridge_best = Ridge(alpha=12)
ridge_best.fit(X_train,y_train)

print("Intercept",ridge_best.intercept_)
print("Coefficient",ridge_best.coef_)

Intercept -60.091254779118316
Coefficient [12.64572918 -0.98122599 26.88080894  0.27999439 -1.34074053  0.30388456
 -2.065459   -0.32944795 -3.78189464 -4.13822208  0.72072583  3.06073687]

### Prediction & Evaluation

In [7]:
#Prediction
train_prediction = ridge_best.predict(X_train)
test_prediction = ridge_best.predict(X_test)

#Evaluation
print("Train r2:",ridge_best.score(X_train,y_train))
print("Test R2:",ridge_best.score(X_test,y_test))

from sklearn.model_selection import cross_val_score
print("Cross validation score:",cross_val_score(ridge_best,X,y,cv=5).mean())

Train r2: 0.6318699334849625
Test R2: 0.6211664104531558
Cross validation score: 0.5693651001043383